### ISSUE TITLE
Add computed edges to BEL Lang Specification YAML file

### ISSUE THREAD

**Issue by wshayes** [belbio/belpy#18]
Add specification to BEL Language YAML file such that we can dynamically define computed edges.

We want to be able to indicate that a complex(p(A), p(B)) has the added computed edges of complex(p(A), p(B)) hasComponent p(A) in the YAML file so these computed edges can be added automatically.

Something like - though I'm not sure the following is correct YAML or will work for our needs:

computed:
    - function: complex
      subject: function
      relationship: hasComponent
      object: parameters
    - function: deg
      subject: function
      relationship: directlyDecreases
      object: parameter

**Comment by davidchen** [comment]
see https://github.com/belbio/belpy/wiki/Computed-Edge-Signatures

**Comment by davidchen** [comment]
see https://github.com/belbio/belpy/wiki/Computed-Edge-Signatures
